// Generated by https://quicktype.io

export interface CryptoDetails {
    data: Crypto; //Aquí está la diferencia respecto al list, aquí no es un array
    timestamp: number;
}

export interface Crypto {
    id: string;
    rank: string;
    symbol: string;
    name: string;
    supply: string;
    maxSupply: null;
    marketCapUsd: string;
    volumeUsd24Hr: string;
    priceUsd: string;
    changePercent24Hr: string;
    vwap24Hr: string;
    explorer: string;
}
